Create ARRAY

In [ ]:
## There are several ways to create arrays. To create an array and to use its methods, first we need to import the NumPy library.

            # import numpy as np
# NumPy is loaded as np (we can assign any name), numpy must be written in lowercase

In [3]:
import numpy as np

In [12]:
# The NumPy’s array() function converts a given list into an array.

array = np.array([10, 20, 30])
array

array([10, 20, 30])

In [7]:
l = [1,2,3,4,"5",6,7,8,9]
print(l)

[1, 2, 3, 4, '5', 6, 7, 8, 9]


In [11]:
arr = np.array([1,2,3,4,"5",6,7,8,9])

print(arr)
print(type(arr))

['1' '2' '3' '4' '5' '6' '7' '8' '9']
<class 'numpy.ndarray'>



Creating a Zero-Dimensional Array

In [15]:
arrzero=np.array(80)
print(arrzero)

print(arrzero.ndim)


80
0


# 1D Array -Creating a 1-D Array
An array with only single row of elements is called 1-D array. 

In [41]:
#Let us try to create a 1-D array from a list which contains numbers as well as strings

array1=np.array([5,-7.4,'a',7.2])
array1

# Observe that since there is a string value in the list, all integer and float values have been promoted to string, while converting the list to array.
# Note: U32 means Unicode-32 data type.

array(['5', '-7.4', 'a', '7.2'], dtype='<U32')

Creating a 2-D Array

In [42]:
array2=np.array([[2.4,3],
                 [4.9,7],
                 [0,-1]])
array2

# Observe that the integers 3, 7, 0 and -1 have been promoted to floats.

array([[ 2.4,  3. ],
       [ 4.9,  7. ],
       [ 0. , -1. ]])

Attributes of NumPy Array

1)    .ndim:  - 
Gives the number of dimensions of the array as an integer value. Arrays can be 1-D, 2-D or n-D.


In [43]:
print(array1.ndim)
print(array2.ndim)

1
2


2.    shape - It gives the sequence of integers indicating the size of the array for each dimension.



In [44]:
print(array.shape)
print(array1.shape)
print(array2.shape)

(3,)
(4,)
(3, 2)


3)  .size: It gives the total number of elements of the array. This is equal to the product of the elements of shape.

In [45]:
print(array.size)
print(array1.size)
print(array2.size)

3
4
6


4)   .dtype:     is the data type of the elements of the array. 
All the elements of an array are of same data type. 
Common data types are int32, int64, float32, float64, U32, etc.

In [46]:
print(array.dtype)
print(array1.dtype)
print(array2.dtype)

int64
<U32
float64


5)     .itemsize:    It specifies the size in bytes of each element of the array. 
Data type int32 and float32 means each element of the array occupies 32 bits in memory. 
8 bits form a byte. Thus, an array of elements of type int32 has itemsize 32/8=4 bytes. 
Likewise, int64/float64 means each item has itemsize 64/8=8 bytes.

In [47]:
print(array.itemsize)
print(array1.itemsize)
print(array2.itemsize)

8
128
8


Other Ways of Creating NumPy Arrays

We can specify data type (integer, float, etc.) while creating array using dtype as an argument to array(). This will convert the data automatically to the mentioned type. In the following example, nested list of integers are passed to the array function. Since data type has been declared as float, the integers are converted to floating point numbers.


In [49]:
array3=np.array([[1,2],[3,4]], dtype=float)
array3

array4p=np.array([3,4],[8,9], dtype=str)
print(arrayp)

TypeError: argument for array() given by name ('dtype') and position (position 1)

2) We can create an array with all elements initialised to 0 using the function zeros(). By default, the data type of the array created by zeros() is float. The following code will create an array with 3 rows and 4 columns with each element set to 0.

In [53]:
array4=np.zeros((3,2))
array4

arrayt=np.zeros((3,5))
arrayt

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3) We can create an array with all elements initialised to 1 using the function ones(). By default, the data type of the array created by ones() is float. The following code will create an array with 3 rows and 2 columns.

In [ ]:
array5=np.ones((3,2)) # first number 3 denotes column while second number 2 denotes rows
array5

# Note- as (dtype=int ) instructions avoided after (3,2) therefore output is in float

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
array5=np.ones((3,2), dtype=int) # first number 3 denotes column while second number 2 denotes rows
array5

# Note- as (dtype=int) instruction ahs been given so now output is in  intiger form

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
np.ones((6, 2, 3))   # Here 6 is no. of matrix to created i.e. sets of -
                        #2 is no. of columns, 3 is no. of rows

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])